language: python
python:
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install -U flake8
script:
- flake8 easy_tokenizer
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tilaboy
  password:
    secure: FMVDtadWeEqfQkdHdG/tx/Q9DKwvP/ATv67BRPZ7K0oEQ2AhFJjBtOEEsRPJIcMy1locCBS9VKLpSiHc50hdRhPQPgU0b5k9O3M0oyS43fpIk0esD1/pb3xDOQgqTFuYWPSQqQ9uTdZex6TxddIjlkROc2tf1KmeBPPTEzsZyVXk4XqpLb69UmqI5vQ9jEVfBYSYZa/QbTM1VJanHYlsDHNBRxcwwZsNf67SOWW35Ckt4usmtqZM8vyDuc96NyuxLCtbIsEfFdgiTfaApM/TqNeBHnfc7C/C9l69yYPScHNmt/7Je7Ggbtf0Zofyq8UNlxeQ9ebQqq0sClCjkm4wNmW4cTwPRUWDnkkM+9QNNMXWEJW3Rlu6ssQiZJmwmGwtvaZLgFSGuXNMXIWhCjxUMsJ/nAdYDQqwWUrrGoCV7F7o/m8X0ljcGRSNi16L6b71tCEIytL5tjX4n5XHPkM2iO9nrB51LG14ZxQ5PG635uKVLOaM+SNboBeDCRV2AIBYNgS1Hhw7T+oe/nUZ9zml0jJVSjLDugtI78GAWhXO7947U5KkjZ8KFRwHbm/G/l57zs4Kz3r4c4d3oMpvb2OneCeTGowzoMlFhhr6o+Q3F+DKSeoOBBL0CM1Hdkd7PB3hguWQA9d4IEmiqRx6knjO+xQ2lEjQoRzXrM73EM/tZYE=
  on:
    tags: true
    repo: tilaboy/easy-tokenizer
    python: 3.6
