language: python
python:
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install -U flake8
script:
- flake8 easy_tokenizer
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tilaboy
  password:
    secure: nczzq7TVljii3d8lhNyylws++kWxkeF5rZvh/hsxpo17V1qI0zI05VrHTddKh5ETMeJ0Yr2OaQCKyKfGTkWdACT8cOUQ79ZpRR9tVuCj2KaJBkksJ3VOUf9fuw1t3bNTaP+K7zDNVw7hb9qMDF+3IKivKYaPjYal7EayPgvmr7HE/6/0IH6AWg2ln9nGPTjVSk60DM/YmBiriKMdfiesE+Mfmv+gs7HcUdi3KWzFE9PhCId1Z83Vq/JGuCmKO2cNXE6KYfuwnLW0wA7lzQcxU946veIPr14vDn5KzNnZ6yk7maacQ+7MFqT+kgiQtIQb4Sa0km+2qoJBpYHWAkd/jpMR9XGNIZR+IdDZaqNi8eObzWxx625Z/ld5AngTzW+YzWlLtsziKRKedZ2VMY6dQGECm2+W9IV9qPdsrMfC+3vYdvVyLZS8/kKkNjvLEXib49mkSGcCL7kIlG0X1XeeQSjDwtuFKcuFBLCvpZTssQ6YuWBNnIKvincg1pDhCRZTZDtRm6788jOk20hP9DgVHNYqs5GF/sR1CRKmNIjHMo/+lKtW6Og2DfdPk2Ua7sMYxIEHUlsCulmnzChyaAMkIYA3XJ4zvyij8zZ2pKA+oaFnIf+jvLuee6bqVjE2Onz3zkgSlBlKbtA5CC6zLuZjYu+lw4mx2SviW+WxXCPYAfE=
  on:
    tags: true
    repo: tilaboy/easy-tokenizer
    python: 3.6
