language: python
python:
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install -U flake8
script:
- flake8 easy_tokenizer
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tilaboy
  password:
    secure: LoosvAtm2ObBdBt5qBfG478oHg1+z8BuIv2KU39b4yAfAtMBWajLopoCSPPfVrrND7liiIndQ0C2LpqBgClLuSd4ZFX7SVmRELe/BeQt7ROV8GTQ19R8+hJcO2j9OMUaSvQAdlk7Jftv4eHH2pwGs0GAeA3m3lOnMvJ6dJiQ1FTH7JeSDbgp6lweP6gOgCy2CJHIzrkDqnoRZ+cHUSkUI99dklLzzq5SUYhJumbh0n5ZZ+5DY9Uq4DQuVHPSIwntcBMJ9GQ43RSwb1uvL6N1CA952y3CSbFJNVlLuPedsyqoNQorf2Pp+mONy9YkAoug/D3TqGjZ6wVDrryJWK/B/0T+N49pfhdqbyKtw3hbx5PXMEnBOTdvROrFciNiG67YfBdr/IKVA5nKUoS9XDgdKVo7fXkMfNgo6lRrcdivRhUH9W0TCpIofEFoV1asGKkbNhxHG0AodaSrF7djwslZ0JJVfApqWKNaQ70NfQtNFhgwxyj2Gd90wMTa9VIPhWzvNc2736EJjw4NnW/cYgJC+OGEEVBDVeXw6gDIXpIRlFREyGRg6wN2h2yZvI3fnua9E5atCoSAt4X5BOR6R47c2Uk/NjCt5zljM+G47PSR59gp2xsCGuxN1FW4aAD517FkjHIsUtQaLj4dePO9updwdIDZKE1B2NaZhZWtPhJflUc=
  on:
    tags: true
    repo: tilaboy/easy-tokenizer
    python: 3.6
