language: python
python:
- 3.7
- 3.6
install:
- pip install -U tox-travis
- pip install -U flake8
script:
- flake8 easy_tokenizer
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tilaboy
  password:
    secure: 12xjJSzet/A6DDZrrIjFBQCQjzxRzW1ObP/l/HBSUunheZV+Je3feMTE1uv0ZEzhfAX5PjNwr0mzKGrsdc8UURYGZLJxgmIh9lcAat2/Uc0FBVQRStAgvnoYpUfGAiHqqbx9J9S/3jmussbrhgabg4mZjoUcFQH8XzRxNhmJFHpiNktWlh/h7YEYmbAjaPFyRf/+BcCUfMsXAbcXMC5Ri+HdppBkdbFkMF0yl6aTRvpO766wgazHenkPvvG3XyeFfdVRCGGk/DHL2jBltcaBMH+DLf/6VTBYYOErEzbJ2ArKfQxbPzk76UTR+7CGdeRRoUT/1T/ShIU54GNp5KqDg2vvhWqwQ5Px9tmL8342NuhLIZfc3y/5I5lr/kIaenW0t8HEO8rxsBFF/jL1ucCz1BRDKlI9OXdiuhbPX9ISZf9HidxUIsFrsjBT0Jki/OyFYI9jFnXEPRVWlVnyrcxFktR1wypCnD4BWh4ZQ6lZQ7lVUCYQO0Ie7afeyPV1P4dtq20HYNrgfH6uLxEYvOQGkdXX1JAWxzjQiAqjp9GypYZCqY52M8CddWdbcCyNQulAy0za9klNMbZjU0MitQCkSEpDO768iplD6eBvCOvT/D3VW739DBo/1Is4m0Q6fFbg+vfMy0HBout1iUdsSrCZ2+Q9tWlI1p3F5SXEf9Z1Vvs=
  on:
    tags: true
    repo: tilaboy/easy-tokenizer
    python: 3.6
